### ISSUE TITLE
support createInstance

### ISSUE THREAD

**Issue by Goldziher** [aveq-research/localforage-asyncstorage-driver#7]
Hi there!

Thanks a lot for this package - its really nifty. In fact I am using it as a dependency in a cache wrapper im working on :). I haven't tested this in live code, but writing jest tests for my package, I noticed something peculiar- 

```
const AsyncStorageDriver = driverWithDefaultSerialization()
await localforage.defineDriver(AsyncStorageDriver)
await localforage.setDriver(AsyncStorageDriver._driver)
//@ts-ignore
console.log(localforage._driver) // "rnAsyncStorageWrapper-withDefaultSerializer"

const instance = localforage.createInstance()

//@ts-ignore
console.log(localforage._config._driver) // "localStorageWrapper"
```

Does this package support instances?

**Comment by Goldziher** [comment]
Hmm. or Im an idiot. Closing this issue...

**Comment by fohletex** [comment]
Okay, no problem. If you still perceive some issues, let me know.

**Comment by Goldziher** [comment]
well, i will suggest adding a paragraph in the docs for making sure to also do this:

```
const instance.createInstance({ driver: AsyncStorageDriver._driver })

``` 

Otherwise the driver is not passed from localForage. I'd assume this is a very "hidden feature" or simply broken localForage functionality 😉

**Comment by fohletex** [comment]
Ah I see. I always did somehow the following as in the LF-docs:

```ts
const instance = localforage.createInstance({ name: 'mySecretInstanceName }); // because I required multiple instances with different names ...
instance.defineDriver(AsyncStorageDriver._driver);
```

:smile: 

I will somehow add it and suggest both solutions...

**Comment by fohletex** [comment]
Added to the docs, see: 74e05164ae4efc52275c10bae43886459df345d0

**Comment by djaffer** [comment]
The documentation misses saying this step which is essential.
instance.defineDriver(AsyncStorageDriver._driver);

**Comment by avivash** [comment]
> ```ts
> instance.defineDriver(AsyncStorageDriver._driver);
> ```

it's worth noting this returns a promise, so you will likely need to do `await instance.defineDriver(AsyncStorageDriver._driver);`, depending how your code is arranged
